# Generated by Django 4.2.14 on 2024-07-27 15:56

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Retreat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('type', models.CharField(max_length=50)),
                ('condition', models.CharField(max_length=50)),
                ('image', models.URLField()),
                ('tag', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_phone', models.CharField(max_length=20)),
                ('retreat_title', models.CharField(max_length=100)),
                ('retreat_location', models.CharField(max_length=100)),
                ('retreat_price', models.FloatField()),
                ('retreat_duration', models.IntegerField()),
                ('payment_details', models.TextField()),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('retreat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retreats.retreat')),
            ],
        ),
    ]
